---
title: PSYC201 Scores
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show
---

```{r setup, include = FALSE}
# load packages
library(knitr)
library(tidyverse)
library(stringr) 
library(lme4)
library(directlabels)
library(DT)
library(broom)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

options(scipen = 1, digits = 3)
theme_set(theme_classic(base_size=16))
```

```{r get_stars, include = F}
get_stars <- function (p) {
    if (p < 0.001) 
        return("***")
    if (p < 0.01) 
        return("**")
    if (p < 0.05) 
        return("*")
    if (p < 0.1) 
        return(".")
    return("")
}
```

Nicely visualize model output
```{r tidy_lmer, include = F}
# Cleans up an lmer output for pretty printing
tidy_lmer <- function(lmer_results, predictors = NA) {
   tidy(lmer_results) %>%
    filter(group == "fixed") %>%
    select(-group) %>%
  # mutate(term = if_else(!is.na(predictors), predictors, term)) %>%
    rowwise() %>%
    mutate(stars = get_stars(p.value)) %>%
    ungroup() %>%
    mutate(p.value = sprintf("%.3f", p.value),
           p.value = ifelse(p.value == "0.000", "< .001", p.value)) %>%
    select(term, estimate, std.error, statistic, p.value, stars) %>%
    rename(`$z$ value` = statistic,
           `$p$ value` = p.value,
           `std. error` = std.error)
}


tidy_lm <- function(lm_results, predictors = NA) {
   tidy(lm_results) %>%
  # mutate(term = if_else(!is.na(predictors), predictors, term)) %>%
    rowwise() %>%
    mutate(stars = get_stars(p.value)) %>%
    ungroup() %>%
    mutate(p.value = sprintf("%.3f", p.value),
           p.value = ifelse(p.value == "0.000", "< .001", p.value)) %>%
    select(term, estimate, std.error, statistic, p.value, stars) %>%
    rename(`$z$ value` = statistic,
           `$p$ value` = p.value,
           `std. error` = std.error)
}
```

## Pre processing

Read in data

```{r load_data}
caos_data <- read_csv("data/caos.csv")
grade_data <- read_csv("data/grades.csv")
```

Munge data
```{r munge_data}
tidy_data <- caos_data %>%
  separate(`STUDENT NAME`, into = c("FirstName", "MiddleName", "LastName"), 
           sep = " ", fill = "right") %>%
  mutate(FirstName = if_else(!is.na(LastName), 
                         paste0(FirstName, " ", MiddleName), FirstName), 
         LastName = if_else(is.na(LastName), MiddleName, LastName)) %>%
  select(-MiddleName) %>%
  right_join(grade_data) %>%
  rename(correctTotal = `PERCENT CORRECT of TOTAL(40)`) %>%
  mutate(Section = factor(Section))
```

Pre-post
```{r pre_post, fig.width = 6, fig.height = 4}
pre_post <- tidy_data %>%
  filter(`MINUTES TO COMPLETE` > 1) %>%
  select(Section, LastName, FirstName, correctTotal, Type) %>%
  filter(!is.na(correctTotal)) %>%
  spread(Type, correctTotal) 

ggplot(pre_post, aes(x = Pre, y = Post, color = Section)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F)

lm(Post ~ Pre + Section, data = pre_post) %>%
  tidy_lm() %>%
  kable()

t.test(pre_post$Post, pre_post$Pre,  paired = T)
```

```{r predict, fig.width = 4, fig.height = 4}
lm(Final ~ correctTotal, filter(tidy_data, Type == "Post")) %>%
  tidy_lm() %>%
  kable()
```
